version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
  # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
  # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
   image: schickling/mailcatcher
   ports: [ 1025, 1080 ]
  mailhog:
   image: mailhog/mailhog
   ports:
       - 8025:8025
  ###< symfony/mailer ###

  php:
    build: docker/php8.2-fpm
    env_file: ./.env
    volumes:
      - ./:/var/www/symfony:cached
    links:
      - database:db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - database:db
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes_from:
      - php
  node:
    image: node:16.16.0
    volumes:
      - ./:/var/www/symfony
    working_dir: /var/www/symfony
    command: bash -c "yarn install && yarn watch"